name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: commplex-bundle
          path: dist

  publish:
    needs: build
    if: github.ref_type == 'tag'
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: commplex-bundle
        path: dist
    - name: Create ZIP
      run: zip -r commplex-bundle.zip dist

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: commplex-bundle.zip

    - name: Authenticate npm
      run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
    - name: Publish package
      working-directory: ./dist
      run: npm publish