name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Create ZIP
        run: zip -r commplex-bundle.zip dist

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: commplex-bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}