name: Publish npm package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.0'
  # release:
    # types: [published]
jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: commplex-bundle

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: Authenticate npm
      run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    - name: Publish package
      working-directory: ./dist
      run: npm publish