name: Tag on Release Branch

on:
  push:
    branches:
      - 'release-*.*.*'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name
        id: extract
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch name: $branch_name"
          version=${branch_name#release-}
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${VERSION}
          git push origin v${VERSION}
